### ISSUE TITLE
bug: Application need restart

### ISSUE THREAD

**Issue by Mehrdad-GH** [auto-wallpaper/auto-wallpaper#19]
### Describe the bug

after you write a prompt you need close and open again app to generate image

**Comment by arashi-dev** [comment]
Thanks Mehrdad for opening the issue.

You mean the "regenerate" button doesn't work? (it has a recycle/refresh icon). If yes, what happens when you click it?

Or you mean the interval?

**Comment by Mehrdad-GH** [comment]
when i click the regenerate button 
It takes a while and does not generate image until i restart it

**Comment by arashi-dev** [comment]
I don't see any problem. Could you please provide your OS information?

**Comment by arashi-dev** [comment]
I just released 0.1.9 version. I fixed a few errors in there. maybe that fixes your problem. 

To update it, just open the app. it will show you an update box automatically.

**Comment by Mehrdad-GH** [comment]
Problem solved well
At the end, thank you for this wonderful project

**Comment by arashi-dev** [comment]
Happy to hear that. Thanks!
