### ISSUE TITLE
feat: Can you help me to start maintain :) ?

### ISSUE THREAD

**Issue by Mahdi-Hazrati** [auto-wallpaper/auto-wallpaper#24]
### Describe the feature you'd like to request

Hello, dear Arash
Very interesting project
I want to start reading and collaborating with this project
But I don't use Tauri anymore,
Can you help me and write a quickstart to run just the project
I want فقط start development :)
Thanks

**Comment by arashi-dev** [comment]
Hi Mahdi. I'm so happy that you are interested :)

Of course! I will add a lil development/contribution tutorial to the documentation by tomorrow.

**Comment by arashi-dev** [comment]
@Mahdi-Hazrati 
Heya!

I've added a brief instruction for development on your local system (https://github.com/auto-wallpaper/auto-wallpaper?tab=readme-ov-file#development-environment)

If you find it confusing or incomplete, feel free to reopen the issue. or open another, if you find another problem during the process. Good Luck! :wink:
