### ISSUE TITLE
bug: `pnpm dev -F tauri-app` Not work!

### ISSUE THREAD

**Issue by Mahdi-Hazrati** [auto-wallpaper/auto-wallpaper#27]
### Describe the bug

Hi Again Arash :)
i hope you doing well
i read your project new document and also read tauri document to install pre requirements of running application i install all step and also run `pnpm install` and install all package.
but when run command to launch development mode, it not run and i got this error,
how to solve this and run application
![Screenshot (339)](https://github.com/auto-wallpaper/auto-wallpaper/assets/127740921/cad484b7-71cd-4dc3-8524-5a57972add5d)

**Comment by arashi-dev** [comment]
Hi, Thanks!

Looks like you don't have `tauri-cli` installed in cargo.
Just simply run this command in the root directory of the project:
```
cargo install tauri-cli --version "1.5.10" --locked
```
